### ISSUE TITLE
KeyError: "None of [Index(['Sandwiches', 'Hamburgers'], dtype='object', name='LabelName')] are in the [index]"

### ISSUE THREAD

**Issue by glenn-jocher** [quiltdata/open-images#1]
In a Google Colab [Notebook](https://colab.research.google.com/drive/1_2-1hSoKUo6YhvmHXVsignDAGm0FAJjd) running the following code produced an error. Code was copied from [link](https://blog.quiltdata.com/how-to-classify-photos-in-600-classes-using-nine-million-open-images-3cdb989ad1c2). What am I doing wrong? Thanks.

```python
pip install ratelim checkpoints
git clone https://github.com/quiltdata/open-images.git
cd open-images/src/openimager
python3 openimager.py "Sandwiches" "Hamburgers"
```

```python
tcmalloc: large alloc 1194041344 bytes == 0x4be78000 @  0x7f8dea3611e7 0x5a1c5c 0x5a5def 0x4f862c 0x4f98c7 0x4f7a28 0x4f876d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f7a28 0x4f876d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128 0x4f7d60 0x4f876d 0x4f98c7 0x4f6128 0x4f9023 0x6415b2 0x64166a
Traceback (most recent call last):
  File "openimager.py", line 89, in <module>
    download(categories)
  File "openimager.py", line 35, in download
    label_map = dict(class_names.set_index('LabelName').loc[categories, 'LabelID']
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 868, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1017, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1902, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1205, in _getitem_iterable
    raise_missing=False)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1246, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)))
KeyError: "None of [Index(['Sandwiches', 'Hamburgers'], dtype='object', name='LabelName')] are in the [index]"
```

<img width="1769" alt="Screenshot 2019-08-04 at 18 26 33" src="https://user-images.githubusercontent.com/26833433/62426453-6b91e400-b6e5-11e9-8f66-12d6481d2bd6.png">

**Comment by ResidentMario** [comment]
There has been [a new release](https://ai.googleblog.com/2019/05/announcing-open-images-v5-and-iccv-2019.html) of the Open Images dataset since this code was written. This article used V4 of the Open Images dataset, and the latest version is now V5. Google made changes to the label names, and also overwrote the old URLs with the new dataset version. The V4 versions of the data are still accessible [here](https://storage.googleapis.com/openimages/web/download_v4.html), but you will need to update the URLs in the code in `openimager.py` to point to the new V4 URLs.
